// ============================================================
// AutoLeave AI – Mock Data & Demo Seed
// ============================================================

window.MOCK_DATA = {
  student: {
    id: 'STU2024001',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@college.edu',
    registerNumber: '21CS1047',
    department: 'Computer Science & Engineering',
    class: 'B.Tech – CSE (3rd Year, Sec-B)',
    semester: '6th Semester',
    rollNumber: '47',
    phone: '+91 98765 43210',
    profileInitials: 'AM',
    profileColor: '#2563EB',
    attendance: 87,
    totalWorkingDays: 120,
    presentDays: 105,
    adviser: 'Dr. Priya Ramachandran',
    adviserEmail: 'priya.r@college.edu',
    joinedDate: '2021-08-01',
  },

  leaveRequests: [
    {
      id: 'LR-2024-001',
      type: 'Medical / Sick Leave',
      typeKey: 'sick',
      reason: 'Severe fever and throat infection. Doctor advised 3 days rest with prescribed medicines.',
      startDate: '2024-03-15',
      endDate: '2024-03-17',
      days: 3,
      appliedDate: '2024-03-14',
      status: 'approved',
      facultyRemark: 'Approved due to valid medical reason. Please submit doctor certificate upon return.',
      aiPrediction: 82,
      aiExplanation: 'High attendance (87%) and valid medical documentation significantly increase approval chances.',
      submittedAt: '2024-03-14T09:30:00Z',
      updatedAt: '2024-03-14T14:15:00Z',
      attachment: null,
      emergencyContact: '+91 98765 43211',
    },
    {
      id: 'LR-2024-002',
      type: 'Personal Leave',
      typeKey: 'personal',
      reason: 'Sister\'s wedding ceremony and family engagement. Need to travel to hometown for 4 days.',
      startDate: '2024-04-22',
      endDate: '2024-04-25',
      days: 4,
      appliedDate: '2024-04-10',
      status: 'pending',
      facultyRemark: null,
      aiPrediction: 64,
      aiExplanation: 'Moderate approval chances. Personal leaves near exam period require additional justification.',
      submittedAt: '2024-04-10T11:00:00Z',
      updatedAt: '2024-04-10T11:00:00Z',
      attachment: null,
      emergencyContact: '+91 98765 43211',
    },
    {
      id: 'LR-2024-003',
      type: 'Emergency Leave',
      typeKey: 'emergency',
      reason: 'Family medical emergency – father hospitalized. Need to travel immediately.',
      startDate: '2024-02-05',
      endDate: '2024-02-07',
      days: 3,
      appliedDate: '2024-02-05',
      status: 'approved',
      facultyRemark: 'Approved. Emergency leave granted. Get well soon to your family.',
      aiPrediction: 91,
      aiExplanation: 'Emergency family situations with immediate travel have historically high approval rates.',
      submittedAt: '2024-02-05T07:45:00Z',
      updatedAt: '2024-02-05T09:00:00Z',
      attachment: null,
      emergencyContact: '+91 77777 88888',
    },
    {
      id: 'LR-2024-004',
      type: 'Personal Leave',
      typeKey: 'personal',
      reason: 'Need to attend cousin\'s function at home. Plan to visit for the weekend extended.',
      startDate: '2024-01-19',
      endDate: '2024-01-22',
      days: 4,
      appliedDate: '2024-01-17',
      status: 'rejected',
      facultyRemark: 'Rejected: Attendance below threshold for extended personal leave during term. Only 2 days may be sanctioned after attendance improvement.',
      aiPrediction: 45,
      aiExplanation: 'Attendance was below 75% threshold during the application period, lowering approval probability.',
      submittedAt: '2024-01-17T10:00:00Z',
      updatedAt: '2024-01-18T16:30:00Z',
      attachment: null,
      emergencyContact: null,
    },
    {
      id: 'LR-2024-005',
      type: 'Medical / Sick Leave',
      typeKey: 'sick',
      reason: 'Viral infection with high fever. Prescribed bed rest by doctor.',
      startDate: '2024-05-08',
      endDate: '2024-05-09',
      days: 2,
      appliedDate: '2024-05-08',
      status: 'pending',
      facultyRemark: null,
      aiPrediction: 78,
      aiExplanation: 'Short medical leave with good attendance record has moderate-high approval probability.',
      submittedAt: '2024-05-08T08:00:00Z',
      updatedAt: '2024-05-08T08:00:00Z',
      attachment: null,
      emergencyContact: null,
    },
  ],

  notifications: [
    {
      id: 'NOTIF-001',
      type: 'approved',
      title: 'Leave Approved ✓',
      message: 'Your sick leave request (LR-2024-001) for Mar 15–17 has been approved by Dr. Priya Ramachandran.',
      timestamp: '2024-03-14T14:15:00Z',
      read: true,
      leaveId: 'LR-2024-001',
      icon: 'CheckCircle',
    },
    {
      id: 'NOTIF-002',
      type: 'under_review',
      title: 'Leave Under Review',
      message: 'Your personal leave request (LR-2024-002) for Apr 22–25 is currently being reviewed.',
      timestamp: '2024-04-10T11:30:00Z',
      read: false,
      leaveId: 'LR-2024-002',
      icon: 'Clock',
    },
    {
      id: 'NOTIF-003',
      type: 'pending',
      title: 'New Leave Submitted',
      message: 'Your sick leave request (LR-2024-005) for May 8–9 has been submitted successfully.',
      timestamp: '2024-05-08T08:01:00Z',
      read: false,
      leaveId: 'LR-2024-005',
      icon: 'FileText',
    },
    {
      id: 'NOTIF-004',
      type: 'rejected',
      title: 'Leave Rejected',
      message: 'Your personal leave request (LR-2024-004) for Jan 19–22 was rejected. Check faculty remarks for details.',
      timestamp: '2024-01-18T16:30:00Z',
      read: true,
      leaveId: 'LR-2024-004',
      icon: 'XCircle',
    },
    {
      id: 'NOTIF-005',
      type: 'reminder',
      title: 'Attendance Reminder',
      message: 'Your current attendance is 87%. Maintain above 75% to remain eligible for leave applications.',
      timestamp: '2024-05-01T09:00:00Z',
      read: false,
      leaveId: null,
      icon: 'AlertTriangle',
    },
    {
      id: 'NOTIF-006',
      type: 'approved',
      title: 'Emergency Leave Approved ✓',
      message: 'Your emergency leave request (LR-2024-003) for Feb 5–7 has been approved.',
      timestamp: '2024-02-05T09:00:00Z',
      read: true,
      leaveId: 'LR-2024-003',
      icon: 'CheckCircle',
    },
    {
      id: 'NOTIF-007',
      type: 'note',
      title: 'Faculty Note Added',
      message: 'Dr. Priya has added a note to your leave record: "Please bring medical certificate on your return."',
      timestamp: '2024-03-18T10:00:00Z',
      read: true,
      leaveId: 'LR-2024-001',
      icon: 'MessageSquare',
    },
  ],

  attendanceHistory: [
    { month: 'Dec', percentage: 72 },
    { month: 'Jan', percentage: 78 },
    { month: 'Feb', percentage: 85 },
    { month: 'Mar', percentage: 83 },
    { month: 'Apr', percentage: 89 },
    { month: 'May', percentage: 87 },
  ],

  leaveTypes: [
    { value: 'sick', label: 'Medical / Sick Leave' },
    { value: 'personal', label: 'Personal Leave' },
    { value: 'emergency', label: 'Emergency Leave' },
    { value: 'academic', label: 'Academic / Event Leave' },
    { value: 'other', label: 'Other' },
  ],
};

window.LEAVE_STATUS_CONFIG = {
  approved: {
    label: 'Approved',
    color: 'green',
    bgClass: 'bg-green-100 dark:bg-green-900/30',
    textClass: 'text-green-700 dark:text-green-400',
    borderClass: 'border-green-200 dark:border-green-800',
    dotClass: 'bg-green-500',
    icon: 'CheckCircle',
  },
  pending: {
    label: 'Pending',
    color: 'amber',
    bgClass: 'bg-amber-100 dark:bg-amber-900/30',
    textClass: 'text-amber-700 dark:text-amber-400',
    borderClass: 'border-amber-200 dark:border-amber-800',
    dotClass: 'bg-amber-500',
    icon: 'Clock',
  },
  rejected: {
    label: 'Rejected',
    color: 'red',
    bgClass: 'bg-red-100 dark:bg-red-900/30',
    textClass: 'text-red-700 dark:text-red-400',
    borderClass: 'border-red-200 dark:border-red-800',
    dotClass: 'bg-red-500',
    icon: 'XCircle',
  },
  under_review: {
    label: 'Under Review',
    color: 'blue',
    bgClass: 'bg-blue-100 dark:bg-blue-900/30',
    textClass: 'text-blue-700 dark:text-blue-400',
    borderClass: 'border-blue-200 dark:border-blue-800',
    dotClass: 'bg-blue-500',
    icon: 'Search',
  },
};

window.NOTIFICATION_TYPE_CONFIG = {
  approved: { color: 'text-green-600 dark:text-green-400', bg: 'bg-green-100 dark:bg-green-900/30' },
  pending: { color: 'text-amber-600 dark:text-amber-400', bg: 'bg-amber-100 dark:bg-amber-900/30' },
  under_review: { color: 'text-blue-600 dark:text-blue-400', bg: 'bg-blue-100 dark:bg-blue-900/30' },
  rejected: { color: 'text-red-600 dark:text-red-400', bg: 'bg-red-100 dark:bg-red-900/30' },
  reminder: { color: 'text-orange-600 dark:text-orange-400', bg: 'bg-orange-100 dark:bg-orange-900/30' },
  note: { color: 'text-purple-600 dark:text-purple-400', bg: 'bg-purple-100 dark:bg-purple-900/30' },
};
